### ISSUE TITLE
RTSC: "Is not recognized as internal or external command"

### ISSUE THREAD

**Issue by Norman-Rodriguez** [Batlez/CloakBox#10]
![Screenshot 2024-07-27 102816](https://github.com/user-attachments/assets/edc77d28-6416-4653-a299-edc3b77fcbb1)
can someone explain what I'm doing wrong I'm continuously getting this error despite creating the VM and following all the necessary steps at least to my knowledge there must be something I'm missing.

**Comment by Batlez** [comment]
You need to link it to where your vboxmanage.exe is.
![324279708-93b09350-86ad-4fb9-966c-ed1f56a12f1e](https://github.com/user-attachments/assets/69c21b72-e264-4e50-bcb7-c12b84f6b5df)
