### ISSUE TITLE
Unable to Use Host PC Microphone and Remove VirtualBox Label in Webcam

### ISSUE THREAD

**Issue by rduran-agsx** [Batlez/CloakBox#20]
## Description
I am trying to use my external microphone from my host PC and remove the "VirtualBox" label from the webcam device inside my VirtualBox virtual machine. However, I'm facing difficulties configuring these settings.

## Request
Any guidance on how to:
- Remove "VirtualBox" from the webcam device name
- Use the host PC's external microphone in the VM

![image](https://github.com/user-attachments/assets/d7bc8f40-ffb5-4d70-a923-fc90bd0be39f)

**Comment by Batlez** [comment]
You can rename the webcam in registry, just search for Virtualbox and then you can rename it to anything you want. For microphone you can see if it appears in Input or Devices, and then see if it works

**Comment by ryprfpryr** [comment]
For others FYI

- To change the label, INSIDE THE VM:
1) Open regedit with CTRL+R > regedit
2) Edit > Search: "VirtualBox"
3) Double click on "FriendlyName" > (Change the text value to desired one)
4) Restart VM

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/b7b7a3c5-afb9-40d7-aa1e-71f9bac90b0e" />
