### ISSUE TITLE
Need help messaged on disc

### ISSUE THREAD

**Issue by 7vn7ins** [Batlez/CloakBox#25]
Hello,

I am trying to follow the instructions but I have run into a few issues when creating the VM. The first is that i get a popup for the driver not running and to disable core integration. The second is that the virtual disk wont create and attach itself to the VM. I have seen that others have the same error when looking at the past tickets, but I tried using their solutions and hasn't worked. I messaged you on Disc, my user is 7vn7ins

**Comment by Batlez** [comment]
Added you on Discord
