### ISSUE TITLE
What Malicious Software Has This Been Tested Against?

### ISSUE THREAD

**Issue by thearchivalone** [Batlez/CloakBox#26]
Hey there. This is primarily just an inquiry due to there not being that many tools like this that are well maintained or production level for use with Virtualbox that are viable for newer malware analysts and researchers. Most options, tutorials and support seem heavily geared towards VMWare and much of that side of the community are not very welcoming to those that use its open source alternatives.

Context: I wrote up my initial findings from about 3 days of trial and error here https://www.reddit.com/r/MalwareAnalysis/comments/1hk0cwz/virtualbox_malware_vm_setups_seem_a_big_mess/ and plan to test out your offering when I get off of work to see how viable it could be as a replacement in my workflow.

Thanks for your time

**Comment by Batlez** [comment]
This is mainly used by people to get by anti cheats and protecting softwares, but it may be beneficial towards malware testing. This version is from Vektor T13, and this was his last 'free' version from 2021, so his newer versions may be even better but unfortunately they cost money.

**Comment by thearchivalone** [comment]
Makes sense. That’s a huge part of why quite a few open source tools for malware analysis just died. People started using them game cheats and some companies started wanting to sue (according to some of the research I’ve done).

I’ll still test this out in case parts of it can fill in parts of the outdated tools that don’t work in modern Virtualbox. Thanks for the response

**Comment by Batlez** [comment]
No problem. Make sure to add me on discord to chat or discuss something afterwards
